name: Mike-Lam
markdown: kramdown
encoding: UTF-8
permalink: /blog/:year/:month/:day/:title
title_en: TestSiteE
title_en: TestSiteF
description_en: A site to test Jekyll
include_lang: y
include_search: y
include_siteBar: y
include_menuBar: y
include_breadcrumb: n
include_footerContactUs: y
include_footerAbout: y
include_footerNews: y
include_footerTwitter: y
